# Generated by Django 2.2.5 on 2020-09-11 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BJ_basedata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productcode', models.CharField(blank=True, max_length=32, null=True, verbose_name='编码')),
                ('description', models.CharField(max_length=512, verbose_name='描述(中文)')),
                ('description_en', models.CharField(max_length=512, verbose_name='描述(英文)')),
                ('unit', models.CharField(max_length=512, verbose_name='单位')),
                ('USD', models.CharField(blank=True, max_length=32, null=True)),
                ('EUR', models.CharField(blank=True, max_length=32, null=True)),
                ('GBP', models.CharField(blank=True, max_length=32, null=True)),
                ('CNY', models.CharField(blank=True, max_length=32, null=True)),
                ('CAD', models.CharField(blank=True, max_length=32, null=True)),
                ('AUD', models.CharField(blank=True, max_length=32, null=True)),
                ('createddate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lastmodifieddate', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '备件数据',
                'verbose_name_plural': '备件数据',
            },
        ),
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='case/%Y/%m/%d', verbose_name='文件名称')),
            ],
        ),
        migrations.CreateModel(
            name='downloadfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('down_file', models.CharField(default=models.DateTimeField(auto_now_add=True), max_length=50)),
            ],
            options={
                'verbose_name': '导出数据',
                'verbose_name_plural': '导出数据',
            },
        ),
        migrations.CreateModel(
            name='FW_basedata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productcode', models.CharField(blank=True, max_length=32, null=True, verbose_name='编码')),
                ('description', models.CharField(max_length=512, verbose_name='描述(中文)')),
                ('description_en', models.CharField(max_length=512, verbose_name='描述(英文)')),
                ('unit', models.CharField(max_length=512, verbose_name='单位')),
                ('USD', models.CharField(blank=True, max_length=32, null=True)),
                ('EUR', models.CharField(blank=True, max_length=32, null=True)),
                ('GBP', models.CharField(blank=True, max_length=32, null=True)),
                ('CNY', models.CharField(blank=True, max_length=32, null=True)),
                ('CAD', models.CharField(blank=True, max_length=32, null=True)),
                ('AUD', models.CharField(blank=True, max_length=32, null=True)),
                ('createddate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lastmodifieddate', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '服务数据',
                'verbose_name_plural': '服务数据',
            },
        ),
        migrations.CreateModel(
            name='importfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file')),
                ('createddate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '导入数据',
                'verbose_name_plural': '导入数据',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_code', models.CharField(max_length=64, unique=True, verbose_name='菜单编码')),
                ('menu_name', models.CharField(max_length=64, unique=True, verbose_name='菜单名称')),
                ('description', models.CharField(max_length=200, verbose_name='菜单描述')),
                ('icon', models.CharField(max_length=32, verbose_name='icon')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_code', models.CharField(max_length=64, unique=True, verbose_name='角色编码')),
                ('role_name', models.CharField(max_length=64, unique=True, verbose_name='角色名称')),
                ('description', models.CharField(max_length=200, verbose_name='角色描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='updatefile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_file', models.FileField(upload_to='update_file')),
                ('lastmodifieddate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '更新数据',
                'verbose_name_plural': '更新数据',
            },
        ),
        migrations.CreateModel(
            name='upsertfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='filename')),
                ('upsertdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '导入/更新数据',
                'verbose_name_plural': '导入/更新数据',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='用户令牌/用户的唯一标识')),
                ('out_time', models.DateTimeField(verbose_name='过期时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='关联的用户')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Role')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserRole',
            },
        ),
        migrations.CreateModel(
            name='RoleMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Menu')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Role')),
            ],
            options={
                'db_table': 'Role_Menu',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='roles',
            field=models.ManyToManyField(through='myapp.RoleMenu', to='myapp.Role'),
        ),
        migrations.CreateModel(
            name='Historicalbasedata',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('productcode', models.CharField(blank=True, max_length=32, null=True, verbose_name='编码')),
                ('name', models.CharField(blank=True, max_length=512, null=True, verbose_name='名称')),
                ('model', models.CharField(blank=True, max_length=512, null=True, verbose_name='型号/类号')),
                ('description', models.CharField(max_length=512, verbose_name='描述')),
                ('product_type', models.CharField(max_length=32, verbose_name='物料类型')),
                ('price_source', models.CharField(choices=[('Pricing', '定价'), ('Quotation', '报价')], max_length=32, verbose_name='价格来源')),
                ('RRP_USD', models.CharField(blank=True, max_length=32, null=True)),
                ('RRP_EUR', models.CharField(blank=True, max_length=32, null=True)),
                ('RRP_GBP', models.CharField(blank=True, max_length=32, null=True)),
                ('RRP_RMB', models.CharField(blank=True, max_length=32, null=True)),
                ('remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注信息')),
                ('createddate', models.DateTimeField(blank=True, editable=False, verbose_name='创建时间')),
                ('lastmodifieddate', models.DateTimeField(blank=True, editable=False, verbose_name='修改时间')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 基础数据',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='basedata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productcode', models.CharField(blank=True, max_length=32, null=True, verbose_name='编码')),
                ('name', models.CharField(blank=True, max_length=512, null=True, verbose_name='名称')),
                ('model', models.CharField(blank=True, max_length=512, null=True, verbose_name='型号/类号')),
                ('description', models.CharField(max_length=512, verbose_name='描述')),
                ('product_type', models.CharField(max_length=32, verbose_name='物料类型')),
                ('price_source', models.CharField(choices=[('Pricing', '定价'), ('Quotation', '报价')], max_length=32, verbose_name='价格来源')),
                ('RRP_USD', models.CharField(blank=True, max_length=32, null=True)),
                ('RRP_EUR', models.CharField(blank=True, max_length=32, null=True)),
                ('RRP_GBP', models.CharField(blank=True, max_length=32, null=True)),
                ('RRP_RMB', models.CharField(blank=True, max_length=32, null=True)),
                ('remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注信息')),
                ('createddate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lastmodifieddate', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '基础数据',
                'verbose_name_plural': '基础数据',
            },
        ),
    ]
